 /*****************************************************************************/
 /***************************  NAME  :  ahmed hassan **************************/
 /***************************  DATE  :  8/15/2023    **************************/
 /***************************  VERSION :  1.0        **************************/
 /*****************************************************************************/
 
#ifndef GPIO_CONFIG_H
#define GPIO_CONFIG_H

/** INITIAL mode OF ALL PINS
            1-  GPIO_u8_INPUT_ANALOG     
            2-  GPIO_u8_INPUT_FLOATING   
            3-  GPIO_u8_INPUT_PU_PD     
				  
            4-  GPIO_u8_OUTPUT_10M_PP   
            5-  GPIO_u8_OUTPUT_10M_OD   
            6-  GPIO_u8_OUTPUT_10M_AF_PP
            7-  GPIO_u8_OUTPUT_10M_AF_OD
			    
            8-  GPIO_u8_OUTPUT_2M_PP    
            9-  GPIO_u8_OUTPUT_2M_OD    
            10- GPIO_u8_OUTPUT_2M_AF_PP 
            11- GPIO_u8_OUTPUT_2M_AF_OD 
			    
            12- GPIO_u8_OUTPUT_50M_PP   
            13- GPIO_u8_OUTPUT_50M_OD   
            14- GPIO_u8_OUTPUT_50M_AF_PP
			15- GPIO_u8_OUTPUT_50M_AF_OD
            
***/
/**PORTA**/

#define GPIO_u8_PA0_INTIAL_MODE          GPIO_u8_OUTPUT_10M_PP
#define GPIO_u8_PA1_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PA2_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PA3_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PA4_INTIAL_MODE          GPIO_u8_OUTPUT_10M_PP
#define GPIO_u8_PA5_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PA6_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PA7_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PA8_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PA9_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PA10_INTIAL_MODE         GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PA11_INTIAL_MODE         GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PA12_INTIAL_MODE         GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PA13_INTIAL_MODE         GPIO_u8_OUTPUT_50M_AF_OD
#define GPIO_u8_PA14_INTIAL_MODE         GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PA15_INTIAL_MODE         GPIO_u8_INPUT_FLOATING

/**PORTB**/

#define GPIO_u8_PB0_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PB1_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PB2_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PB3_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PB4_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PB5_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PB6_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PB7_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PB8_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PB9_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PB10_INTIAL_MODE         GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PB11_INTIAL_MODE         GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PB12_INTIAL_MODE         GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PB13_INTIAL_MODE         GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PB14_INTIAL_MODE         GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PB15_INTIAL_MODE         GPIO_u8_INPUT_FLOATING

/**PORTC**/

#define GPIO_u8_PC0_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PC1_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PC2_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PC3_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PC4_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PC5_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PC6_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PC7_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PC8_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PC9_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PC10_INTIAL_MODE         GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PC11_INTIAL_MODE         GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PC12_INTIAL_MODE         GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PC13_INTIAL_MODE         GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PC14_INTIAL_MODE         GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PC15_INTIAL_MODE         GPIO_u8_INPUT_FLOATING

/**PORTD**/

#define GPIO_u8_PD0_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PD1_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PD2_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PD3_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PD4_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PD5_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PD6_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PD7_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PD8_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PD9_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PD10_INTIAL_MODE         GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PD11_INTIAL_MODE         GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PD12_INTIAL_MODE         GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PD13_INTIAL_MODE         GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PD14_INTIAL_MODE         GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PD15_INTIAL_MODE         GPIO_u8_INPUT_FLOATING

/**PORTE**/

#define GPIO_u8_PE0_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PE1_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PE2_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PE3_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PE4_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PE5_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PE6_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PE7_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PE8_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PE9_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PE10_INTIAL_MODE         GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PE11_INTIAL_MODE         GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PE12_INTIAL_MODE         GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PE13_INTIAL_MODE         GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PE14_INTIAL_MODE         GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PE15_INTIAL_MODE         GPIO_u8_INPUT_FLOATING

/**PORTF**/

#define GPIO_u8_PF0_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PF1_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PF2_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PF3_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PF4_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PF5_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PF6_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PF7_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PF8_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PF9_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PF10_INTIAL_MODE         GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PF11_INTIAL_MODE         GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PF12_INTIAL_MODE         GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PF13_INTIAL_MODE         GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PF14_INTIAL_MODE         GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PF15_INTIAL_MODE         GPIO_u8_INPUT_FLOATING

/**PORTG**/

#define GPIO_u8_PG0_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PG1_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PG2_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PG3_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PG4_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PG5_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PG6_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PG7_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PG8_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PG9_INTIAL_MODE          GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PG10_INTIAL_MODE         GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PG11_INTIAL_MODE         GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PG12_INTIAL_MODE         GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PG13_INTIAL_MODE         GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PG14_INTIAL_MODE         GPIO_u8_INPUT_FLOATING
#define GPIO_u8_PG15_INTIAL_MODE         GPIO_u8_INPUT_FLOATING


/** INITIAL VALUE OF ALL PINS
  OPTIONS   1-GPIO_u8_INPUT_PD
            2-GPIO_u8_INPUT_PU
			3-GPIO_u8_OUTPUT_Push       
			4-GPIO_u8_OUTPUT_Pull       
			5-GPIO_u8_OUTPUT_OD_LOW     
            6-GPIO_u8_OUTPUT_OD_FLOATING
*/

/**PORTA**/


#define GPIO_u8_PA0_INTIAL_VALUE        GPIO_u8_INPUT_PU
#define GPIO_u8_PA1_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PA2_INTIAL_VALUE        GPIO_u8_INPUT_PU
#define GPIO_u8_PA3_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PA4_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PA5_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PA6_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PA7_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PA8_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PA9_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PA10_INTIAL_VALUE       GPIO_u8_INPUT_PD
#define GPIO_u8_PA11_INTIAL_VALUE       GPIO_u8_INPUT_PD
#define GPIO_u8_PA12_INTIAL_VALUE       GPIO_u8_INPUT_PD
#define GPIO_u8_PA13_INTIAL_VALUE       GPIO_u8_INPUT_PU
#define GPIO_u8_PA14_INTIAL_VALUE       GPIO_u8_INPUT_PD
#define GPIO_u8_PA15_INTIAL_VALUE       GPIO_u8_INPUT_PD

/**PORTB**/

#define GPIO_u8_PB0_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PB1_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PB2_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PB3_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PB4_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PB5_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PB6_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PB7_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PB8_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PB9_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PB10_INTIAL_VALUE       GPIO_u8_INPUT_PD
#define GPIO_u8_PB11_INTIAL_VALUE       GPIO_u8_INPUT_PD
#define GPIO_u8_PB12_INTIAL_VALUE       GPIO_u8_INPUT_PD
#define GPIO_u8_PB13_INTIAL_VALUE       GPIO_u8_INPUT_PD
#define GPIO_u8_PB14_INTIAL_VALUE       GPIO_u8_INPUT_PD
#define GPIO_u8_PB15_INTIAL_VALUE       GPIO_u8_INPUT_PD

/**PORTC**/

#define GPIO_u8_PC0_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PC1_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PC2_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PC3_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PC4_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PC5_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PC6_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PC7_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PC8_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PC9_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PC10_INTIAL_VALUE       GPIO_u8_INPUT_PD
#define GPIO_u8_PC11_INTIAL_VALUE       GPIO_u8_INPUT_PD
#define GPIO_u8_PC12_INTIAL_VALUE       GPIO_u8_INPUT_PD
#define GPIO_u8_PC13_INTIAL_VALUE       GPIO_u8_INPUT_PD
#define GPIO_u8_PC14_INTIAL_VALUE       GPIO_u8_INPUT_PD
#define GPIO_u8_PC15_INTIAL_VALUE       GPIO_u8_INPUT_PD

/**PORTD**/

#define GPIO_u8_PD0_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PD1_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PD2_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PD3_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PD4_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PD5_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PD6_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PD7_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PD8_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PD9_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PD10_INTIAL_VALUE       GPIO_u8_INPUT_PD
#define GPIO_u8_PD11_INTIAL_VALUE       GPIO_u8_INPUT_PD
#define GPIO_u8_PD12_INTIAL_VALUE       GPIO_u8_INPUT_PD
#define GPIO_u8_PD13_INTIAL_VALUE       GPIO_u8_INPUT_PD
#define GPIO_u8_PD14_INTIAL_VALUE       GPIO_u8_INPUT_PD
#define GPIO_u8_PD15_INTIAL_VALUE       GPIO_u8_INPUT_PD

/**PORTE**/

#define GPIO_u8_PE0_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PE1_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PE2_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PE3_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PE4_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PE5_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PE6_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PE7_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PE8_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PE9_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PE10_INTIAL_VALUE       GPIO_u8_INPUT_PD
#define GPIO_u8_PE11_INTIAL_VALUE       GPIO_u8_INPUT_PD
#define GPIO_u8_PE12_INTIAL_VALUE       GPIO_u8_INPUT_PD
#define GPIO_u8_PE13_INTIAL_VALUE       GPIO_u8_INPUT_PD
#define GPIO_u8_PE14_INTIAL_VALUE       GPIO_u8_INPUT_PD
#define GPIO_u8_PE15_INTIAL_VALUE       GPIO_u8_INPUT_PD

/**PORTF**/

#define GPIO_u8_PF0_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PF1_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PF2_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PF3_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PF4_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PF5_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PF6_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PF7_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PF8_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PF9_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PF10_INTIAL_VALUE       GPIO_u8_INPUT_PD
#define GPIO_u8_PF11_INTIAL_VALUE       GPIO_u8_INPUT_PD
#define GPIO_u8_PF12_INTIAL_VALUE       GPIO_u8_INPUT_PD
#define GPIO_u8_PF13_INTIAL_VALUE       GPIO_u8_INPUT_PD
#define GPIO_u8_PF14_INTIAL_VALUE       GPIO_u8_INPUT_PD
#define GPIO_u8_PF15_INTIAL_VALUE       GPIO_u8_INPUT_PD

/**PORTG**/

#define GPIO_u8_PG0_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PG1_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PG2_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PG3_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PG4_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PG5_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PG6_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PG7_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PG8_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PG9_INTIAL_VALUE        GPIO_u8_INPUT_PD
#define GPIO_u8_PG10_INTIAL_VALUE       GPIO_u8_INPUT_PD
#define GPIO_u8_PG11_INTIAL_VALUE       GPIO_u8_INPUT_PD
#define GPIO_u8_PG12_INTIAL_VALUE       GPIO_u8_INPUT_PD
#define GPIO_u8_PG13_INTIAL_VALUE       GPIO_u8_INPUT_PD
#define GPIO_u8_PG14_INTIAL_VALUE       GPIO_u8_INPUT_PD
#define GPIO_u8_PG15_INTIAL_VALUE       GPIO_u8_INPUT_PD

#endif
